aradin:
   cache:
      redis:
         defaults:
            ttl: PT60M #https://blog.csdn.net/huang007guo/article/details/81625061
            cache-null-values: true
            key-prefix: header
            use-key-prefix: true
         configs:
            cacheA:
               ttl: PT2H
               cache-null-values: true
               key-prefix: header
               use-key-prefix: true
spring:
   redis:
      database: 0 # Redis数据库索引（默认为0）
      host: 127.0.0.1# Redis服务器地址
      port: 6379# Redis服务器连接端口
      password: 123456# Redis服务器连接密码（默认为空）
      timeout: 1000 # 连接超时时间（毫秒）
      pool:
         max-total:  100 # 连接池最大连接数（使用负值表示没有限制）
         max-waitMillis: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-idle: 50 # 连接池中的最大空闲连接
         min-idle: 10 # 连接池中的最小空闲连接
         testObBorrow: true