aradin:
  version:
    nacos:
      group: 
      data-id: 
spring:
  cloud:
    nacos:
      username: 
      password: 
      config:
        enabled: true
        server-addr: ip:port,,
        namespace: 