aradin:
  swagger:
    base-package: 
    ant-path: 
    title: 
    description: 
    version: 
    enable: true
    auth: false
    contact-name: daliu
    contact-email: liudaax@126.com
    contact-url: 
    license:
    license-url: 
    use-default-status: 